name: 'Skip CI'
description: 'Skip ci based on some input parameter'
author: 'Michael Wittwer <michael.wittwer@shiftcode.ch>'
inputs:
  skipOnCommitMsg:
    description: 'will cancel the current action if the commit message contains given value'
    default: ''
    required: true
runs:
  using: 'node12'
  main: 'lib/main.js'
