# check doc on https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs
name: 'Skip CI'
description: 'Sets output param depending on commit message'
author: 'shiftcode GmbH <team@shiftcode.ch>'
inputs:
  skipOnCommitMsg:
    description: 'defines an output variable depending if the commit message contains the skipOnCommitMsg string (output: true) or not (false).'
    default: ''
    required: true
  githubToken:
    description: 'github token necessary to fetch the commit message with sha of commit triggering this workflow'
    default: ''
    required: true
outputs:
  shouldExecute:
    description: 'boolean value. True if the commit message contains the string provided in skipOnCommitMsg input param, false otherwise.'
runs:
  using: 'node16'
  main: 'dist/index.js'
