name: "Test typescript-action"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Check for Execution
        uses: ./
        with:
          skipOnCommitMsg: "sample"
          ghToken: ${{secrets.GH_TOKEN_3}}
      - name: Some Job
        run: echo "sample"
