name: "Test typescript-action"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.1.1
      - name: Install Node (v20) 
        id: node-install
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.11
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Check for Execution
        uses: ./
        with:
          skipOnCommitMsg: "sample"
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Some Job
        run: echo "sample"
